### ISSUE TITLE
WebViews and Apps

### ISSUE THREAD

**Issue by mrego** [Igalia/webengineshackfest#11]
## Logistics

* Facilitator: @JonasKruckenberg (Tauri team member & DevRel at CrabNebula)
* Date & Time: [Wednesday 7th at 12:00 CEST (local time)](https://www.timeanddate.com/worldclock/fixedtime.html?iso=20230607T1000)
* URL: https://meet.jit.si/Web-Engines-Hackfest-2023-WebViews-Apps

## Description

The web has proven itself as useful for building standalone apps too (electron) but it's not always perfect (large size, missing support, native integration challenges) and other solutions aren't perfect either (Tauri is heavily using system WebViews). 

Let's talk about current challenges, what we can do to improve the current situation and dream about the future of apps together

## Agenda

TBD

**Comment by JonasKruckenberg** [comment]
Alright so rough agenda,
1. Introductions
2. Quick primer on webviews and webview usages
3. Collect issues, grievances, and experiences from the group
4. Discussion
5. Collect ideas, proposals and possible ways forward on the previously collected issues
6. Wrap up

**Comment by mrego** [comment]
Notes at https://github.com/Igalia/webengineshackfest/wiki/2023-WevViews-and-Apps
