### ISSUE TITLE
Chromium / Wayland

### ISSUE THREAD

**Issue by mrego** [Igalia/webengineshackfest#13]
## Logistics

* Facilitator: @tonikitoo (Igalia)
* Date & Time: [Tuesday 6th at 15:00 CEST (local time)](https://www.timeanddate.com/worldclock/fixedtime.html?iso=20230606T1300)
* URL: https://meet.jit.si/Web-Engines-Hackfest-2023-Chromium-Wayland

## Description

Wayland's adoption is steadily growing, with some Linux distributions already shipping with it as the default. Thus, more and more users expect support for it from applications, which can be a non-trivial task for developers - especially for such complex apps as browsers.

This breakout session will walkthrough all phases of the Chromium port to Wayland, its origins, difficulties, status and future plan. Being a complex and extremely popular application, the adventure adds up some lessons of how to do and not to do things :)

## Agenda

- Introduction
  - round table and gather particular topics attendees what to discuss   
  - Some relevant concepts
- A quick history about how the Chrome/Wayland port has evolved
- Adoption of Wayland by desktop and embedded communities/environment overall
- The main difficulties to launch it
- Demonstration (linux desktop, chromeos)

**Comment by MaxIhlenfeldt** [comment]
@tonikitoo not sure if you want to keep the description I initially wrote for this, feel free to change it :)

**Comment by nikolaszimmermann** [comment]
I'm very interested in this session :-)
I would love to hear about the history about Ozone/Wayland, the advent of the custom Wayland protocols (e.g. the explicit sync stuff), the role of sync fences, DRM planes, etc.

**Comment by tonikitoo** [comment]
> 

@msisov 💪

**Comment by tonikitoo** [comment]
now we have an agenda 👍

**Comment by tonikitoo** [comment]
cc @nickdiego @MaxIhlenfeldt

**Comment by mrego** [comment]
Do we have notes of this session?

**Comment by mrego** [comment]
Closing as it seems we don't have notes for this.
