### ISSUE TITLE
WinterCG

### ISSUE THREAD

**Issue by mrego** [Igalia/webengineshackfest#14]
## Logistics

* Facilitator: @andreubotella (Igalia)
* Date & Time: [Tuesday 6th at 10:00 CEST (local time)](https://www.timeanddate.com/worldclock/fixedtime.html?iso=20230606T0800)
* URL: https://meet.jit.si/Web-Engines-Hackfest-2023-WinterCG

## Description

WinterCG is a W3C community group that aims to provide a space for JavaScript server-side runtimes to collaborate on API interoperability. This is done by collaborating on API additions to the web platform that would benefit such runtimes, as well as by documenting existing behaviors.

## Agenda

- Introduction
- What's in scope for the WinterCG?
  - Web-interoperability versus non-web cross-runtime interoperability
  - Our work on web standards and TC39
  - How do non-DOM graphical runtimes (e.g. NativeScript) relate?
- WinterCG conformance and runtime keys
  - What does it mean to be WinterCG conformant? (e.g. Node.js has long-standing differences with the web in, say, `setTimeout` that other server-side runtimes don't have)
  - WinterCG test suite / fork of WPT

**Comment by andreubotella** [comment]
The plan for the agenda is: 

- What's in scope for the WinterCG?
  - Web-interoperability versus non-web cross-runtime interoperability
  - How do non-DOM graphical runtimes (e.g. NativeScript) relate?
  - Web spec vs TC39 work (e.g. `AsyncContext`)
- Runtime keys and WinterCG test suite
  - Should we have a WinterCG fork of WPT?

**Comment by spectranaut** [comment]
Link for notes:
https://notes.igalia.com/YbGF7z3eQ86Cf7Prz-kWnA#
