### ISSUE TITLE
Servo

### ISSUE THREAD

**Issue by mrego** [Igalia/webengineshackfest#16]
## Logistics

* Facilitator: @mrobinson (Igalia)
* Date & Time: [Wednesday 7th at 10:00 CEST (local time)](https://www.timeanddate.com/worldclock/fixedtime.html?iso=20230607T0800)
* URL: https://meet.jit.si/Web-Engines-Hackfest-2023-Servo

## Description

A breakout session dealing with Servo and Rust on the web platform

## Agenda

TBD

**Comment by Loirooriol** [comment]
One point of the agenda could be talking about the style upgrade and how to keep it synced with gecko.

**Comment by mrobinson** [comment]
Topics to consider:
 - How to manage style upgrades and keeping in sync with upstream in the Gecko repository. We could also chat about WebRender here.
 - An embedding API for Servo / allowing Servo to be used in rust projects without compilation
 - Making Servo easier to work on / pain points for developers

**Comment by mrego** [comment]
Notes at https://github.com/Igalia/webengineshackfest/wiki/2023-Servo
