### ISSUE TITLE
Updates on accelerated compositing in WebKitGTK

### ISSUE THREAD

**Issue by mrego** [Igalia/webengineshackfest#18]
## Logistics

* Facilitator: @carlosgcampos (Igalia)
* Date & Time: [Tuesday 6th at 12:00 CEST (local time)](https://www.timeanddate.com/worldclock/fixedtime.html?iso=20230606T1000)
* URL: https://meet.jit.si/Web-Engines-Hackfest-2023-Accelerated-Compositing-WebKitGTK

## Description

Session to discuss the new buffer sharing approach to implement accelerated compositing in WebKitGTK

## Agenda

* Intro
* Explanation of DMA-BUF renderer in WebKitGTK
* Questions/Discussion

**Comment by carlosgcampos** [comment]
It's a breakout session, but my plan is to give a short talk about what we have done so far and then discuss about it

**Comment by mrego** [comment]
Notes at https://github.com/Igalia/webengineshackfest/wiki/2023-Updates_on_accelerated_compositing_in_WebKitGTK

**Comment by mrego** [comment]
Notes at https://github.com/Igalia/webengineshackfest/wiki/2023-Updates_on_accelerated_compositing_in_WebKitGTK
