### ISSUE TITLE
Getting into web engine contributing

### ISSUE THREAD

**Issue by mrego** [Igalia/webengineshackfest#20]
## Logistics

* Facilitator: @CanadaHonk
* Date & Time: [Wednesday 7th at 12:00 CEST (local time)](https://www.timeanddate.com/worldclock/fixedtime.html?iso=20230607T1000)
* URL: https://meet.jit.si/Web-Engines-Hackfest-2023-Web-engine-contributing

## Description

In January, I began contributing to web engines (Gecko/Firefox) for the first time. Since then I have been hooked and it's been a pleasant experience throughout which I feel more people could get into and enjoy, contributing to web engines and the broader web standard/ecosystem.

In this session I would go over my experience starting out and how vendors could help improve the experience, and to try and encourage more people to contribute!

## Agenda

- Intro (whoami, etc)
- Overview on contributing to different engines (comparing each engine's platforms for code/bugs/chat?/etc)
- How *I* got started contributing to Gecko and some quick highlights of things done/shipped
- Rundown of the entire process for a few engines (setting up local dev, coding, committing, reviews) mostly for showcasing ease of use/development / first time contributors
- Notes of common missing docs, etc in most engines
- Call to action that more people should contribute :)
- Questions

**Comment by CanadaHonk** [comment]
My plan for the agenda is roughly:
- Intro (whoami, etc)
- Overview on contributing to different engines (comparing each engine's platforms for code/bugs/chat?/etc)
- How *I* got started contributing to Gecko and some quick highlights of things done/shipped
- Rundown of the entire process for a few engines (setting up local dev, coding, committing, reviews) mostly for showcasing ease of use/development / first time contributors
- Notes of common missing docs, etc in most engines
- Call to action that more people should contribute :)
- Questions

**Comment by mrego** [comment]
Notes at https://github.com/Igalia/webengineshackfest/wiki/2023-Getting-into-web-engine-contributing
