### ISSUE TITLE
Improving developer experience through standards

### ISSUE THREAD

**Issue by littledan** [Igalia/webengineshackfest#21]
# Logistics

* Facilitator: @littledan (Bloomberg)
* Date & Time: [Wednesday 7th at 15:00 CEST (local time)](https://www.timeanddate.com/worldclock/fixedtime.html?iso=20230607T1300)
* URL: https://meet.jit.si/Web-Engines-Hackfest-2023-Developer-experience-standards

# Description

New web platform features are typically about capabilities, whereas improvements in developer experience usually come through tools, frameworks, and browser devtools. But does it make sense to work on improving developer experience through standards efforts? In some cases, I think so--a source maps standards effort is spinning up now, as TC39-TG4 ([TC39 presentation](https://docs.google.com/presentation/d/10nYC0dD-CWXnmPtqeuQMVM15b8kWMgrIS6j2G2wpoyw/edit#slide=id.g24095b33afb_0_89)). Let's discuss what sorts of opportunities exist in this space. [Or, if people are interested, I could go into some depth on source maps.]

# Agenda

1. What developer experience shortcomings do we see in the web today?
2. Which kinds of things make sense to do collectively vs individually?
3. Description of the source maps effort

**Comment by mrego** [comment]
Do we have notes of this session?

**Comment by mrego** [comment]
Closing as it seems we don't have notes for this.
