### ISSUE TITLE
How to build a new feature for the web platform — and make it a success with developers

### ISSUE THREAD

**Issue by sideshowbarker** [Igalia/webengineshackfest#24]
### Logistics

* Date & Time: [Tuesday 4th June at 16:30 CEST (local time)](https://www.timeanddate.com/worldclock/fixedtime.html?iso=20240604T1430)
* URL: https://meet.jit.si/WEH2024-New-Web-Platform-Feature
* Notes: https://github.com/Igalia/webengineshackfest/wiki/2024-How-to-build-a-new-feature-for-the-web-platform

### Facilitator(s)

@sideshowbarker 

…with: @annevk • @keithamus • @domfarolino • @spectranaut • @lukewarlow • @alice 

### Summary

The goal of this session is to explore and discuss how to best get new features for the platform successfully created, implemented, tested, documented, and adopted — with active participation from some specific attendees who’ve had experience in each of those areas and who can offer particular “lessons learned” insights and tips. Also:

- [documenting](https://github.com/Igalia/webengineshackfest/wiki/Building-new-features-for-the-web-platform) the process/advice (brainstorming, with the goal of writing something up from the session notes)
- discussing ways in which the existing process might be improved
- answering questions about parts of the process that may be especially mysterious to most people

### Type

Onsite

### Agenda

We’ll follow the [“How to facilitate a breakout discussion”](https://gist.github.com/spectranaut/d000bcc297005c262b711c117c770b22) guidelines, and aim to make this a very interactive session — with the following _“How to build a new feature for the web platform”_ outline helping to guide the discussion:

_11-step process (zero-indexed, in hex):_

0. Describing the problem: What specific problem are you trying to solve. Who are you trying to solve it for?
1. Proposing a solution; writing a good explainer with a problem description + proposed solution (**optional/`TODO` step**)
2. Initiating and leading a focused discussion in a spec issue tracker about the problem and possible solutions.
3. Putting together a spec or spec PR for a problem solution (and learning spec-publishing tools and their quirks).
4. Writing good WPTs and getting attention for them from reviewers.
5. Using browser-project bug/issue trackers to raise compelling implementation requests.
6. Contributing an implementation patch to a browser project (and learning the project’s patch-contribution process).
7.  Getting documentation written for your feature in MDN (working with MDN writers/editors and technical reviewers).
8. Driving web-developer adoption through outreach in places where web-developers pay attention.
9. Monitoring web-developer experience/success and identifying web-developer pain points/frustrations.

   A.  Iterating over each step as needed (including, going back to step <span>#</span>0 and repeating the whole cycle)

_＊ Common off-by-one error many folks make: starting at step <span>#</span>1 (proposing solutions without first describing problems)._

### Resources

- [The history of focus-visible and inert](https://www.igalia.com/chats/alice-and-rob) — success story

---
- [HTML Design Principles](https://www.w3.org/TR/html-design-principles/#toc) — the “ten commandments” of web-platform feature development
-  [LXJS 2013 - Domenic Denicola - How to win friends and influence standards bodies](https://www.youtube.com/watch?v=hneN6aW-d9w)
 - [Hitchhiker's Guide to Web Standards // Dominic Farolino // CascadiaJS 2018](https://www.youtube.com/watch?v=z2SbknMWtp0)
- [How to Win Friends and Influence People](https://archive.org/details/bwb_KS-365-216/) — 1936 book by Dale Carnegie (pioneer “motivational speaker”)
- [Tips for effective explainers](https://tag.w3.org/explainers/#tips-for-effective-explainers) — W3C Tag document
- https://ian.hixie.ch/bible/handling-people — the secret sauce

---
- https://whatwg.org/faq#adding-new-features
- https://whatwg.org/working-mode
- https://whatwg.org/stages
---
- https://www.w3.org/community/about/faq/#how-do-i-propose-a-group
- https://www.w3.org/community/about/tool/ • https://github.com/w3c-cg → `https:​//w3c-cg.github.io/my-feature`
- https://www.w3.org/community/about/faq/#how-do-we-publish-a-report
---
- https://wicg.io/#proposals
- https://github.com/WICG/admin/blob/gh-pages/README.md#contributing-new-proposals
- https://github.com/WICG/starter-kit
---
- https://github.com/tc39/ecma402/blob/main/CONTRIBUTING.md
- https://tc39.es/process-document/
---
- https://web-platform-tests.org/writing-tests/
- https://github.com/tc39/test262/blob/main/CONTRIBUTING.md
---
- https://webkit.org/contributing-code/
- https://firefox-source-docs.mozilla.org/
- https://chromium.googlesource.com/chromium/src/+/refs/heads/main/docs/contributing.md
---
- https://github.com/mdn/content/blob/main/CONTRIBUTING.md
---

**Comment by mrego** [comment]
The notes from the session have been moved to the wiki: https://github.com/Igalia/webengineshackfest/wiki/2024-How-to-build-a-new-feature-for-the-web-platform

Not sure if someone wants to make a high level summary at https://github.com/Igalia/webengineshackfest/wiki/Building-new-features-for-the-web-platform or somewhere else.

**Comment by mrego** [comment]
I'm going to close this issue, if someone wants to add some more links or something, they can just do it in a new comment.
