### ISSUE TITLE
JavaScript standardization

### ISSUE THREAD

**Issue by ryzokuken** [Igalia/webengineshackfest#25]
### Logistics

* Date & Time: [Wednesday 5th June at 12:00 CEST (local time)](https://www.timeanddate.com/worldclock/fixedtime.html?iso=20240605T1000)
* URL: https://meet.jit.si/WEH2024-JavaScript-Standardization
* Notes: https://github.com/Igalia/webengineshackfest/wiki/2024-JavaScript-standardization

### Facilitator(s)

@ryzokuken (@Igalia)

### Summary

If enough attendees are interested in the subject, given that a number of TC39 delegates and otherwise noteworthy JavaScript developers would be around, we should organize a session around JS standardization aimed at bringing ongoing TC39 work to the rest of the room, facilitating discussion and soliciting feedback on design and future shape of current proposals.

### Type

Onsite

**Comment by mrego** [comment]
It looks like this session has an agenda don topics but not actual minutes: https://github.com/Igalia/webengineshackfest/wiki/2024-JavaScript-standardization

If someone has some notes about this session, feel free to update the content on the wiki. Thanks!

**Comment by mrego** [comment]
I'm going to close the issue, if at some point we have some notes we can still add them to the wiki later and link them in a new comment here.
