### ISSUE TITLE
Standardization across layers: Experiences with HTML, JS and Unicode

### ISSUE THREAD

**Issue by littledan** [Igalia/webengineshackfest#27]
### Logistics

* Date & Time: [Tuesday 4th June at 12:00 CEST (local time)](https://www.timeanddate.com/worldclock/fixedtime.html?iso=20240604T1000)
* URL: https://meet.jit.si/WEH2024-Standardization
* Notes: https://github.com/Igalia/webengineshackfest/wiki/2024-Standardization-across-layers

### Facilitator(s)

@littledan

### Summary

A number of web platform standards efforts traverse multiple layers of the stack. This involves working with different groups of people who are experts in their respective areas and have varying decision-making processes. Let's review some past cases (e.g., modules, BigInt, Intl), and discuss current ongoing efforts, including:
- MessageFormat
- AsyncContext
- ShadowRealms
- Signals
- modules (again)

### Type

Onsite

**Comment by mrego** [comment]
Notes have been moved to the wiki: https://github.com/Igalia/webengineshackfest/wiki/2024-Standardization-across-layers
