### ISSUE TITLE
Servo

### ISSUE THREAD

**Issue by mrobinson** [Igalia/webengineshackfest#28]
### Logistics

* Date & Time: [Tuesday 4th June at 15:00 CEST (local time)](https://www.timeanddate.com/worldclock/fixedtime.html?iso=20240604T1300)
* URL: https://meet.jit.si/WEH2024-Servo
* Notes: https://github.com/Igalia/webengineshackfest/wiki/2024-Servo

### Facilitator(s)

@mrobinson

### Summary

A session for those interested in the Servo web rendering engine. Topics of discussion will be gathered at the start of the session depending on who is there and what interests people.

### Type

Onsite

**Comment by nicoburns** [comment]
I would be keen to discuss:

#### 1. Layout
- Architecture: how different layout modes communicate with each other (layout/measure/inline_sizes methods, etc)
- Direct use of Taffy for Flexbox/CSS Grid/non-flow
 
#### 2. Licensing
- Possibility of more new servo code being MIT/Apache 2.0 licensed (or MIT/Apache 2.0/MPL tri-licensed) for interop with the wider Rust UI ecosystem.
- (Table layout code might be a good trial case if we can get consensus from Martin/Oriol/Rahki about reliscensing the existing code as MIT/Apache2.0/MPL)

**Comment by mrego** [comment]
Notes have been moved to the wiki: https://github.com/Igalia/webengineshackfest/wiki/2024-Servo
