### ISSUE TITLE
Demoing the new WebKit Container SDK

### ISSUE THREAD

**Issue by TingPing** [Igalia/webengineshackfest#31]
### Logistics

* Date & Time: [Tuesday 4th June at 12:00 CEST (local time)](https://www.timeanddate.com/worldclock/fixedtime.html?iso=20240604T1000)
* URL: https://meet.jit.si/WEH2024-WebKit-SDK
* Notes: https://github.com/Igalia/webengineshackfest/wiki/2024-Demoing-the-new-WebKit-Container-SDK

### Facilitator(s)

@TingPing (Igalia)

### Summary

Discussions around Igalia's new [SDK](https://github.com/Igalia/webkit-container-sdk) for Linux.

In this session we can discuss how the SDK works and its motivations. As well as showing off some common and more advanced workflows.

### Type

Onsite

**Comment by mrego** [comment]
Notes have been moved to the wiki: https://github.com/Igalia/webengineshackfest/wiki/2024-Demoing-the-new-WebKit-Container-SDK

@TingPing could you please add a link to the slides in the wiki page? Once that's done we can close this issue. Thanks!

**Comment by TingPing** [comment]
Slides: https://notes.igalia.com/p/DQI8U3r7q#/

**Comment by TingPing** [comment]
Added.
