### ISSUE TITLE
Trusted Types and The Sanitizer API

### ISSUE THREAD

**Issue by bkardell** [Igalia/webengineshackfest#32]
### Logistics

* Date & Time: [Tuesday 4th June at 15:00 CEST (local time)](https://www.timeanddate.com/worldclock/fixedtime.html?iso=20240604T1300)
* URL: https://meet.jit.si/WEH2024-Trusted-Types
* Notes: https://github.com/Igalia/webengineshackfest/wiki/2024-Trusted-Types-and-The-Sanitizer-API

### Facilitator(s)

@bkardell @lukewarlow 

### Summary

Igalia has been working on Trusted Types. We'll present the state of things for v1, as well as introduce some related topics for v2 discussions:

* unsafe-hashes 
* Sanitizer API: current status of discussions and plans around it/imagining ways forward to disable the legacy types that are so problematic.
* new keyword (name TBD) for handling `eval()` better [See 473](https://github.com/w3c/trusted-types/issues/473). It would cause `eval()` to throw in browsers that support CSP but don't support the new keyword.  Its main benefit then is that it blocks random uses of `eval()` which are not `TrustedScript` and allows authors to control handles to policies which are more easily reviewed.

### Type

Onsite

**Comment by mrego** [comment]
Notes moved to the wiki: https://github.com/Igalia/webengineshackfest/wiki/2024-Trusted-Types-and-The-Sanitizer-API
