### ISSUE TITLE
Compiling JavaScript ahead of time

### ISSUE THREAD

**Issue by CanadaHonk** [Igalia/webengineshackfest#33]
### Logistics

* Date & Time: [Wednesday 5th June at 16:30 CEST (local time)](https://www.timeanddate.com/worldclock/fixedtime.html?iso=20240605T1430)
* URL: https://meet.jit.si/WEH2024-Compiling-JavaScript

### Facilitator(s)

@CanadaHonk

### Summary

Compiling JavaScript ahead of time (AOT) has always been theoretically possible but most people doubt the efficacy of it. [Porffor](https://porffor.dev) is a ~new (almost 1 year old) novel hobby JS engine/runtime/compiler experimenting with entirely AOT compilation of JS to WebAssembly. Compiling to Wasm ahead of time allows for interesting abilities like compiling JS to C, producing tiny native binaries; using type annotations via TypeScript for optimization; safety via Wasm sandboxing while maintaining much greater performance than interpreters; and likely more opportunities not yet thought of. In this session, we will demo what is currently achieved with JS AOT compilation and discuss what place it could have in the JavaScript ecosystem in the future.

### Type

Onsite

### Other comments

~~Might be too niche? ([twitter poll](https://twitter.com/CanadaHonk/status/1788213062798922055))~~

**Comment by CanadaHonk** [comment]
https://docs.google.com/presentation/d/1LPLGjKR-UDynar6CNkHj7rbFrNerOUm0643nMowMWRE/edit?usp=sharing

**Comment by mrego** [comment]
It seems this session has no notes, if someone took some notes, please upload them to the wiki. Thanks!

**Comment by mrego** [comment]
I'm going to close the issue, if at some point we have some notes we can still add them to the wiki later and link them in a new comment here.
