### ISSUE TITLE
WPE-Android status update

### ISSUE THREAD

**Issue by zhani** [Igalia/webengineshackfest#34]
### Logistics

* Date & Time: [Wednesday 5th June at 15:00 CEST (local time)](https://www.timeanddate.com/worldclock/fixedtime.html?iso=20240605T1300)
* URL: https://meet.jit.si/WEH2024-WPE-Android
* Notes: https://github.com/Igalia/webengineshackfest/wiki/2024-WPE-Android-status-update

### Facilitator(s)

@zhani

### Summary

Status update of what's going on with WPE-Android project. Brief overview what the project is about, the goals for this year and show some demos.

### Type

Onsite

**Comment by mrego** [comment]
Notes have been moved to the wiki: https://github.com/Igalia/webengineshackfest/wiki/2024-WPE-Android-status-update
