### ISSUE TITLE
Wolvic: a browser for WebXR applications

### ISSUE THREAD

**Issue by javifernandez** [Igalia/webengineshackfest#35]
### Logistics

* Date & Time: [Tuesday 4th June at 16:30 CEST (local time)](https://www.timeanddate.com/worldclock/fixedtime.html?iso=20240604T1430)
* URL: https://meet.jit.si/WEH2024-Wolvic
* Notes: https://github.com/Igalia/webengineshackfest/wiki/2024-Wolvic

### Facilitator(s)

@javifernandez (Igalia)

### Summary

In this breakout session I'd like to introduce the Wolvic browser for XR devices. We will talk about its main WebXR related capabilities and architecture. 

The breakout session will also focus on the role of the web in the XR domain and why an open source alternative is key for this ecosystem. 

### Type

Onsite

**Comment by mrego** [comment]
Notes have been moved to the wiki: https://github.com/Igalia/webengineshackfest/wiki/2024-Wolvic
