### ISSUE TITLE
WebKit and Skia

### ISSUE THREAD

**Issue by carlosgcampos** [Igalia/webengineshackfest#36]
### Logistics

* Date & Time: [Wednesday 5th June at 12:00 CEST (local time)](https://www.timeanddate.com/worldclock/fixedtime.html?iso=20240605T1000)
* URL: https://meet.jit.si/WEH2024-WebKit-Skia
* Notes: https://hackmd.io/@rego/weh2024-36/edit

### Facilitator(s)

@carlosgcampos,@alexgcastro

### Summary

Talk about the current status of Skia in WebKit and future plans

### Type

Remote

**Comment by mrego** [comment]
Notes have been moved to https://github.com/Igalia/webengineshackfest/wiki/2024-WebKit-and-Skia
