### ISSUE TITLE
Reference Targets for Cross-Shadow Root IDREF associations

### ISSUE THREAD

**Issue by alice** [Igalia/webengineshackfest#38]
### Logistics

* Date & Time: [Wednesday 5th June at 16:30 CEST (local time)](https://www.timeanddate.com/worldclock/fixedtime.html?iso=20240605T1430)
* URL: https://meet.jit.si/WEH2024-Cross-Shadow-Root
* Notes: https://github.com/Igalia/webengineshackfest/wiki/2024-Reference-Targets-for-Cross-Shadow-Root-IDREF-associations
* Slides: https://notes.igalia.com/p/QGPBcdgGn#/

### Facilitator(s)

@alice (Igalia)

### Summary

We met [last year](https://github.com/Igalia/webengineshackfest/issues/10) to discuss how we might approach the problem of cross-shadow root IDREFs.

Since then, we've explored two ideas:

- [Exporting IDs from shadow roots](https://github.com/WICG/aom/blob/gh-pages/exportid-explainer.md), and
- [Reference Target](https://github.com/WICG/aom/blob/gh-pages/reference-target-explainer.md)

Reference Targets would allow a shadow host to specify an element within its shadow root which should act as the target for an ID reference referring to the host. This would allow the host to encapsulate elements which nonetheless need to be able to be targeted by ID references to provide certain functionality. This idea has promising support from members of the Web Components community with an interest in Web Components accessibility.

In this session we can discuss both the current proposal and the [considered alternatives](https://github.com/WICG/aom/blob/gh-pages/reference-target-explainer.md#considered-alternatives), and discuss what work is remaining to potentially specify, prototype and ship this proposal.

### Type

Onsite

**Comment by alice** [comment]
I made a Matrix channel: #wicg-aom:matrix.org

**Comment by mrego** [comment]
Notes have been moved to the wiki: https://github.com/Igalia/webengineshackfest/wiki/2024-Reference-Targets-for-Cross-Shadow-Root-IDREF-associations
